### ISSUE TITLE
ionic-ng-boilerplate vs https://github.com/diegonetto/generator-ionic?

### ISSUE THREAD

**Issue by steve21124** [apompa/ionic-ng-boilerplate#1]
great implementation.. So why someone one to use ionic-ng-boilerplate instead of generator-ionic? 

thanks

**Comment by apompa** [comment]
Thanks!

They are different implemantation with the same goal. If someone is used to ng-boilerplate already for his work with AngularJs this framework will be pretty starightforward to use!

This one generates 2 working environments, development (grunt build - build folder output) and production ready code (grunt compile - www folder output) which minifies and optimizes in several ways the code (checkout $templateCache and html2Js).

So this one works better for me, but try both and use the one you work better with! ;)

**Comment by steve21124** [comment]
another one is https://github.com/loicknuchel/ionic-boilerplate

**Comment by apompa** [comment]
Hope this was usefull to you!
